/**
 * Source-backed network command type identifiers.
 *
 * Source references:
 * - Generals/Code/GameEngine/Include/GameNetwork/NetworkDefs.h (enum NetCommandType)
 */

export const NETCOMMANDTYPE_UNKNOWN = -1;
export const NETCOMMANDTYPE_ACKBOTH = 0;
export const NETCOMMANDTYPE_ACKSTAGE1 = 1;
export const NETCOMMANDTYPE_ACKSTAGE2 = 2;
export const NETCOMMANDTYPE_FRAMEINFO = 3;
export const NETCOMMANDTYPE_GAMECOMMAND = 4;
export const NETCOMMANDTYPE_PLAYERLEAVE = 5;
export const NETCOMMANDTYPE_RUNAHEADMETRICS = 6;
export const NETCOMMANDTYPE_RUNAHEAD = 7;
export const NETCOMMANDTYPE_DESTROYPLAYER = 8;
export const NETCOMMANDTYPE_KEEPALIVE = 9;
export const NETCOMMANDTYPE_DISCONNECTCHAT = 10;
export const NETCOMMANDTYPE_CHAT = 11;
export const NETCOMMANDTYPE_MANGLERQUERY = 12;
export const NETCOMMANDTYPE_MANGLERRESPONSE = 13;
export const NETCOMMANDTYPE_PROGRESS = 14;
export const NETCOMMANDTYPE_LOADCOMPLETE = 15;
export const NETCOMMANDTYPE_TIMEOUTSTART = 16;
export const NETCOMMANDTYPE_WRAPPER = 17;
export const NETCOMMANDTYPE_FILE = 18;
export const NETCOMMANDTYPE_FILEANNOUNCE = 19;
export const NETCOMMANDTYPE_FILEPROGRESS = 20;
export const NETCOMMANDTYPE_FRAMERESENDREQUEST = 21;
export const NETCOMMANDTYPE_DISCONNECTSTART = 22;
export const NETCOMMANDTYPE_DISCONNECTKEEPALIVE = 23;
export const NETCOMMANDTYPE_DISCONNECTPLAYER = 24;
export const NETCOMMANDTYPE_PACKETROUTERQUERY = 25;
export const NETCOMMANDTYPE_PACKETROUTERACK = 26;
export const NETCOMMANDTYPE_DISCONNECTVOTE = 27;
export const NETCOMMANDTYPE_DISCONNECTFRAME = 28;
export const NETCOMMANDTYPE_DISCONNECTSCREENOFF = 29;
export const NETCOMMANDTYPE_DISCONNECTEND = 30;
export const NETCOMMANDTYPE_MAX = 31;
