import { describe, expect, it } from 'vitest';

import {
  NETCOMMANDTYPE_ACKBOTH,
  NETCOMMANDTYPE_ACKSTAGE1,
  NETCOMMANDTYPE_ACKSTAGE2,
  NETCOMMANDTYPE_CHAT,
  NETCOMMANDTYPE_DISCONNECTEND,
  NETCOMMANDTYPE_DISCONNECTKEEPALIVE,
  NETCOMMANDTYPE_DISCONNECTPLAYER,
  NETCOMMANDTYPE_DISCONNECTSCREENOFF,
  NETCOMMANDTYPE_DISCONNECTSTART,
  NETCOMMANDTYPE_DISCONNECTVOTE,
  NETCOMMANDTYPE_FILEANNOUNCE,
  NETCOMMANDTYPE_FILEPROGRESS,
  NETCOMMANDTYPE_FRAMEINFO,
  NETCOMMANDTYPE_GAMECOMMAND,
  NETCOMMANDTYPE_KEEPALIVE,
  NETCOMMANDTYPE_LOADCOMPLETE,
  NETCOMMANDTYPE_MANGLERQUERY,
  NETCOMMANDTYPE_MANGLERRESPONSE,
  NETCOMMANDTYPE_MAX,
  NETCOMMANDTYPE_PACKETROUTERACK,
  NETCOMMANDTYPE_PACKETROUTERQUERY,
  NETCOMMANDTYPE_PROGRESS,
  NETCOMMANDTYPE_RUNAHEAD,
  NETCOMMANDTYPE_RUNAHEADMETRICS,
  NETCOMMANDTYPE_TIMEOUTSTART,
  NETCOMMANDTYPE_WRAPPER,
} from './network-command-type.js';

describe('network command type constants', () => {
  it('match NetCommandType values from NetworkDefs.h', () => {
    expect(NETCOMMANDTYPE_ACKBOTH).toBe(0);
    expect(NETCOMMANDTYPE_ACKSTAGE1).toBe(1);
    expect(NETCOMMANDTYPE_ACKSTAGE2).toBe(2);
    expect(NETCOMMANDTYPE_FRAMEINFO).toBe(3);
    expect(NETCOMMANDTYPE_GAMECOMMAND).toBe(4);
    expect(NETCOMMANDTYPE_RUNAHEADMETRICS).toBe(6);
    expect(NETCOMMANDTYPE_RUNAHEAD).toBe(7);
    expect(NETCOMMANDTYPE_KEEPALIVE).toBe(9);
    expect(NETCOMMANDTYPE_CHAT).toBe(11);
    expect(NETCOMMANDTYPE_MANGLERQUERY).toBe(12);
    expect(NETCOMMANDTYPE_MANGLERRESPONSE).toBe(13);
    expect(NETCOMMANDTYPE_PROGRESS).toBe(14);
    expect(NETCOMMANDTYPE_LOADCOMPLETE).toBe(15);
    expect(NETCOMMANDTYPE_TIMEOUTSTART).toBe(16);
    expect(NETCOMMANDTYPE_WRAPPER).toBe(17);
    expect(NETCOMMANDTYPE_FILEANNOUNCE).toBe(19);
    expect(NETCOMMANDTYPE_FILEPROGRESS).toBe(20);
  });

  it('keeps disconnect-range command block contiguous', () => {
    expect(NETCOMMANDTYPE_DISCONNECTSTART).toBe(22);
    expect(NETCOMMANDTYPE_DISCONNECTKEEPALIVE).toBe(23);
    expect(NETCOMMANDTYPE_DISCONNECTPLAYER).toBe(24);
    expect(NETCOMMANDTYPE_PACKETROUTERQUERY).toBe(25);
    expect(NETCOMMANDTYPE_PACKETROUTERACK).toBe(26);
    expect(NETCOMMANDTYPE_DISCONNECTVOTE).toBe(27);
    expect(NETCOMMANDTYPE_DISCONNECTSCREENOFF).toBe(29);
    expect(NETCOMMANDTYPE_DISCONNECTEND).toBe(30);
    expect(NETCOMMANDTYPE_MAX).toBe(31);
  });
});
